### ISSUE TITLE
[file browser] symbolic-linked images do not show show up in the file list

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#1]
Please refer to set_QA folder. There should be many other images.

**Comment by pford** [comment]
Checked set_QA folder, list is still missing many items.  Reopening issue.

**Comment by pford** [comment]
In my local build I can see symbol-linked files (e.g. fits image) and folders (e.g. CASA image).  Asked Anthony for a detailed os file listing.

**Comment by kswang1029** [comment]
[root@acdc0 set_QA]# ls -lh
total 114M
lrwxrwxrwx 1 root root   64 Oct 18 10:11 G14.114-0.574.continuum.image.pbcor.fits -> /scratch/Images/set_G14/G14.114-0.574.continuum.image.pbcor.fits
lrwxrwxrwx 1 root root   37 Oct 15 14:00 G34mm1.miriad -> /scratch/Images/set_G34/G34mm1.miriad
lrwxrwxrwx 1 root root   62 Dec  4 11:23 G34mm1_lsb_all.uv.part1.line.natwt.sml -> /scratch/Images/set_G34/G34mm1_lsb_all.uv.part1.line.natwt.sml
lrwxrwxrwx 1 root root   56 Dec  4 09:33 HH211_IQU_zoom_4ch.image.pbcor -> /scratch/Images/set_HH211/HH211_IQU_zoom_4ch.image.pbcor
lrwxrwxrwx 1 root root   59 Nov 14 15:23 OrionKL_sci.spw19.cube.I.pbcor.fits -> /scratch/Images/set_OMC/OrionKL_sci.spw19.cube.I.pbcor.fits
lrwxrwxrwx 1 root root   60 Oct 15 13:58 S255_IR_sci.spw25.cube.I.pbcor.fits -> /scratch/Images/set_S255/S255_IR_sci.spw25.cube.I.pbcor.fits
lrwxrwxrwx 1 root root   48 Oct 15 13:59 SDC335.579-0.292.spw0.line.image -> /scratch/Images/SDC335.579-0.292.spw0.line.image
lrwxrwxrwx 1 root root   38 Nov 14 15:23 SgrB2-N.spw0.line.fits -> /scratch/Images/SgrB2-N.spw0.line.fits
lrwxrwxrwx 1 root root   33 Oct 16 15:50 br1202_wide.image -> /scratch/Images/br1202_wide.image
lrwxrwxrwx 1 root root   37 Oct 17 16:01 broken_header.miriad -> /scratch/Images/set_G34/G34mm1.miriad
lrwxrwxrwx 1 root root   51 Nov 14 13:16 cluster_00128.fits -> /scratch/Images/set_imagePyramid/cluster_00128.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:16 cluster_00256.fits -> /scratch/Images/set_imagePyramid/cluster_00256.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:16 cluster_00512.fits -> /scratch/Images/set_imagePyramid/cluster_00512.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:16 cluster_01024.fits -> /scratch/Images/set_imagePyramid/cluster_01024.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:17 cluster_02048.fits -> /scratch/Images/set_imagePyramid/cluster_02048.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:17 cluster_04096.fits -> /scratch/Images/set_imagePyramid/cluster_04096.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:17 cluster_08192.fits -> /scratch/Images/set_imagePyramid/cluster_08192.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:17 cluster_16384.fits -> /scratch/Images/set_imagePyramid/cluster_16384.fits
lrwxrwxrwx 1 root root   51 Nov 14 13:17 cluster_32768.fits -> /scratch/Images/set_imagePyramid/cluster_32768.fits
drwxr-xr-x 2 root root 4.0K Oct 15 14:04 empty.fits
drwxr-xr-x 2 root root 4.0K Oct 15 14:03 empty.image
drwxr-xr-x 2 root root 4.0K Oct 15 14:04 empty.miriad
-rw-r--r-- 1 root root    0 Oct 15 14:02 empty.txt
-rw-r--r-- 1 root root    0 Oct 15 14:04 empty2.fits
-rw-r--r-- 1 root root    0 Oct 15 14:07 empty2.image
-rw-r--r-- 1 root root    0 Oct 15 14:07 empty2.miriad
drwxr-xr-x 2 root root 4.0K Oct 15 13:57 empty_folder
lrwxrwxrwx 1 root root   51 Oct 17 10:24 hugeGaussian10k.fits -> /scratch/Images/set_Gaussian2D/hugeGaussian10k.fits
lrwxrwxrwx 1 root root   51 Oct 17 10:24 hugeGaussian20k.fits -> /scratch/Images/set_Gaussian2D/hugeGaussian20k.fits
lrwxrwxrwx 1 root root   51 Nov 14 12:46 hugeGaussian40k.fits -> /scratch/Images/set_Gaussian2D/hugeGaussian40k.fits
lrwxrwxrwx 1 root root   51 Nov 14 12:46 hugeGaussian80k.fits -> /scratch/Images/set_Gaussian2D/hugeGaussian80k.fits
-rw-r--r-- 1 root root 114M Nov 28 09:22 orion_12co_hera.hdf5
-rw-r--r-- 1 root root  43K Oct 17 10:04 qa_xyProfiler.fits

**Comment by pford** [comment]
Discussed with Anthony.  NRAO backend is run in a Docker container, which does not follow symlinks unless you also bind mount the linked-to directory.  It is possible this could be fixed with Docker settings on startup for the nrao backend, but I do not think it is a backend issue.  When running my developer build pointing to the same directory as my docker container, I see the symbolic-linked images in the file list.

**Comment by ajm-asiaa** [comment]
test
