### ISSUE TITLE
[file info] pixel increment 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#11]
The entry "Pixel increment" in the file info now adopts the unit defined in the header. To have a better UX, please transform it to user friendly units, like milliarcsec, arcsec, arcmin, or degree, depending on the value itself. If it is velocity, please use km/s.

**Comment by duidae** [comment]
fixed in https://github.com/CARTAvis/nrao-carta-backend/pull/15
