### ISSUE TITLE
[xyz cursor profiler] better not showing xyz profiles before moving the cursor inside the raster image during the image open process

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#12]
When opening a large image, xy (and perhaps z) profiles shows up before the raster image showing up. It is better to start to show the profiles when cursor starts its journey inside the image. This could save some computation energies when opening a large image and most importantly, later we will have some pre-defined GUI layouts which may not have xy or z profilers as default. So there is no point to keep sending profiles to the frontend while there is no corresponding GUI widget.

**Comment by pford** [comment]
The backend no longer sends spatial profiles until requirements are set and SET_CURSOR is sent.  However, the frontend seems to keep the last image's profile plot but updates the range for the new image.  Will discuss in weekly meeting.
