### ISSUE TITLE
[image viewer] missing image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#20]
Tested with desktop version v1.0-beta2 mac: http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta2.dmg

To reproduce:
1) open cluster_08192.fits (https://drive.google.com/file/d/1kZxZmOq8VaPo7dRT9_Af6nYwIl8WoACn/view?usp=sharing)
2) then open cluster_00128.fits (not append)(https://drive.google.com/file/d/10_B3hDhfQdxD_XCsrUSdaGZqSuPd6Fs9/view?usp=sharing) 
3) cluster_00128.fits should be opened but there is no image shown.

The pattern is like open a big xy image, then a small xy image.

**Comment by pford** [comment]
This works for me on my OSX dev build and on Docker ubuntu build.  It may be related to other issues, please try again after latest commit builds.

**Comment by kswang1029** [comment]
Yes, the symptom is gone. Thanks a lot!
