### ISSUE TITLE
[file browser] ignore hidden folders

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#21]
Currently all folders, including hidden folders, are shown in the file list. We may consider to ignore hidden folders since mostly they are not for storing images. This would improve the UX if we use <home> as the default image path (usually there are many hidden folders created by various applications).

**Comment by pford** [comment]
Just committed a fix for this (for a simple change, I don't make a branch and PR).  Backend ignores filenames (a directory is casacore::File) which start with '.'

**Comment by kswang1029** [comment]
Tested.
