### ISSUE TITLE
[File info]Get file info from a non-existent file

### ISSUE THREAD

**Issue by zarda** [CARTAvis/nrao-carta-backend#28]
In case an user try to get file info from  “no_such_file.image” which does not exist. The FILE_INFO_RESPONSE can not return.

**Comment by duidae** [comment]
fixed in https://github.com/CARTAvis/nrao-carta-backend/pull/31

**Comment by zarda** [comment]
Another testing non-existent file makes backend to crash.

### Fatal Error [(NOT SET)]:  Bad number of dimensions for ~/CARTA/Images/set_QA/broken_header.miriad in XYOPEN
Assertion failed: (err == 0), function uv_loop_delete, file src/uv-common.c, line 691.
Abort trap: 6

**Comment by kswang1029** [comment]
this issue does not match issue #28. A new one is created and this is should be closed.
