### ISSUE TITLE
[file browser] wrong file size at root image path

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#32]
test version: http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta3.dmg (electron app on mac)

The file sizes of h_m51_xxx are not correct. 

<img width="1198" alt="screen shot 2018-12-19 at 14 54 02" src="https://user-images.githubusercontent.com/20819712/50203957-23b08d80-039e-11e9-9db8-891e3aa09f7a.png">

When dive further in the file structure, file sizes are okay.

**Comment by pford** [comment]
For symlinked files, returned size of link not file.  This has been fixed in master.
