### ISSUE TITLE
cube histogram is corrupt if a channel histogram is requested first

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/nrao-carta-backend#36]
Thanks to @kswang1029 for spotting this.
Per-cube histograms are incorrect if a per-cube histogram has been requested first. To reproduce:
- Load an image
- Change to another channel
- Select a cube histogram from the render config widget

![image](https://user-images.githubusercontent.com/592504/50291248-b7ee2380-0476-11e9-91bb-acf236885c2f.png)

@kswang1029 has verified that the region histogram data arriving at the frontend seems to have a large number of overflow elements in it
<img width="221" alt="screen shot 2018-12-20 at 22 45 43" src="https://user-images.githubusercontent.com/592504/50291353-0dc2cb80-0477-11e9-89a4-dff624b88a44.png">

**Comment by kswang1029** [comment]
I was not able to reproduce this issue this morning. I guess the new commits fix the issue. Will keep an eye on it. So far so good now! Thanks!
