### ISSUE TITLE
partial update of cube histogram should show current histogram

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/nrao-carta-backend#37]
Currently, the cube histogram is blank until `progress == 1`. The partial updates should include the current state of the histogram (once the max/min have been determined). That way, the user can get a rough estimate of the cube histogram as it is calculated.

**Comment by pford** [comment]
Added this in branch pam/cubeHistogramUpdate.  Shall I proceed with pull request for version 1.0, or wait until after release?  It is really a minor change, added the Histogram submessage in each progress message.

**Comment by veggiesaurus** [comment]
@pford Partial updates work nicely, thanks. You can merge it in for V1.0

**Comment by pford** [comment]
Fixed in PR #43
