### ISSUE TITLE
cube histograms should not have fewer bins than channel histograms

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/nrao-carta-backend#38]
The number of bins for a channel histogram is calculated as _sqrt(width * height) = sqrt(N)_, where _N_ is the number of data points. This is a common approach to estimating the number of bins without any prior knowledge of the data's distribution. 

For the cube histogram, the number of bins is calculated as _cbrt(N)_, where _N_ is the number of data points. This leads to situations where there are fewer bins in a cube histogram than a channel histogram. 

We have a few possible options here:
1. Use the same number of bins for cube histograms and channel histograms, for consistency
2. Use the sqrt(N) rule for cube histograms as well, which may lead to a very large number of bins for large cubes
3. Use the sqrt(N) rule with some upper bound (e.g. 10 000 bins)
4. Choose a different approach entirely, such as Sturges' formula (https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width)

My suggestion would be either (1) or (3). @kswang1029, thoughts? It's difficult to know what a sensible bin width would be without first doing some investigation of the data.

**Comment by pford** [comment]
Juergen agreed with (1) so that is what I implemented.  With the short timeframe for version 1.0 packages, unless we extend the deadline any further modification should be for 1.1.

**Comment by veggiesaurus** [comment]
closing this, as the fix has been merged in
