### ISSUE TITLE
memory leak when stepping through channels

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/nrao-carta-backend#41]
Stepping through channels or playing an animation results in a memory leak. Tested with the latest ubuntu appimage.

To reproduce: 
- Open appimage. `carta_backend` starts with roughly 6 MB of memory utilised
- Load `supermosaic.10.fits`. `carta_backend` memory usage increases to around 66 MB
- Step through the channels using the _Next_ button. Memory usage increases in increments of about 60 MB when new channels are loaded (but not _every_ new channel results in an increase)
- Play an animation. Memory usage increases slowly as the animation is played back. Currently sitting at 1.9 GB after a few playbacks

**Comment by veggiesaurus** [comment]
for comparison, when using the old IDIA hdf5_image_viewer backend, memory usage peaks at 43 MB when loading `supermosaic.10.hdf5`. 

Two observations:
- The reason loading a slice of supermosiac.10 adds 60 MB to memory usage in the current backend (rather than 30 MB, which is the size of the slice on disk) is probably due to loading the slice in casacore before copying it to a raw array. Not sure how to get around that
- The increase is probably related to threading, as it gets worse when playing animations.

**Comment by ajm-asiaa** [comment]
Just in case you don't know, the Linux v1.0 release versions are running carta_backend with twice the number of default threads. That is because, when we did some testing, the performance appeared to be greater when set to use more than the default number of threads.

In the run.sh script we have the following lines:
`X=2`
`NPROCS=$(getconf _NPROCESSORS_CONF)`
`NTHREADS=$((NPROCS*X))`
 
Then: 
`$dirname/carta_backend threads=$NTHREADS`

It is possible to modify this if further testing is needed. AppImages can be easily extracted: 
> ./CARTA-v1.0-ubuntu.AppImage --appimage-extract

They extract to a directory called `squashfs-root`.

Then the run.sh script can be directly accessed and modified:
> squashfs-root/resources/app/carta-backend/bin/run.sh

and CARTA can be started again:
> /squashfs-root/AppRun

**Comment by veggiesaurus** [comment]
@ajm-asiaa thanks, I'll see if that reduces the rate at which the memory leak increases. We may need to tune this thread count in future, since most of the threads get blocked by I/O, and generally, we don't want more threads than the number of logical cores when executing CPU-intensive code.

**Comment by pford** [comment]
The channel histograms were being cached, fixing it to keep the latest one only.

**Comment by ajm-asiaa** [comment]
I have replaced the carta-backend with Pam's fixed version in the following ubuntu AppImage for testing:
http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta5-ubuntu-x86_64.AppImage

As with the previous version, it is set to use double the amount of default threads for now. 

I have not updated the Mac or RedHat versions with the fix yet.

**Comment by veggiesaurus** [comment]
thanks @ajm-asiaa , testing the build now. It still seems to slowing increase in memory. This time, it leveled off at about 1.5 GB (down from 1.9 GB). However, loading a different file didn't result in the memory increasing any further (whereas before it would increase again), so could this be related to casacore caching things? (in which case, it's a _good_ thing)

@pam After giving it some thought, I don't think removing the channel histograms cache is the answer, at least until the file is closed. I don't think that was the source of our issues. For the file I was testing (supermosaic), there would be 2776 bins per histogram. That means roughly 11 kB per channel histogram, or 2.3 MB for all the channel histograms in the 200 channel cube. That's not a problem at all, and it would help to keep histograms cached, so that animations are considerably faster the second run through. @kswang1029 has mentioned this before a few times, so perhaps he can weigh in on it.

**Comment by kswang1029** [comment]
I second Angus’ suggestions. Indeed, having per channel histogram cached in memory while an image is loaded helps a lot in animation. What remains is how we have a good guess of n_bins to adopt. Using geometric mean of xy pixels (even if it is a cube) is a good start. We probably can have an minimum and maximum n_bins to handle small images and very large images well.

**Comment by pford** [comment]
Per-channel histograms are cached.  According to the OSX Activity Monitor, the memory used for the supermosaic image animation varied between 42 MB (same as image loaded), 71 MB, and 100 MB, most likely depending on how many threads were caching a channel at once.  The memory never exceeded 100 MB, unlike the original report of 1.9 GB.

**Comment by pford** [comment]
Pull request #44
