### ISSUE TITLE
memory leak when calculating cube histogram

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/nrao-carta-backend#42]
(possibly related to #41)

Requesting a cube histogram results in a memory leak. Tested with the latest ubuntu appimage.

To reproduce: 
- Open appimage. `carta_backend` starts with roughly 6 MB of memory utilised
- Load `supermosaic.10.fits`. `carta_backend` memory usage increases to around 66 MB
- Switch to a cube histogram. During the calculation, memory usage increases to around 2.9 GB

**Comment by pford** [comment]
Yes, same as issue #41.  SET_IMAGE_CHANNELS generates a channel histogram.

**Comment by veggiesaurus** [comment]
@pford testing the new build Anthony made. Calculating a cube histogram now no longer causes  a massive memory leak. However, repeatedly loading a file and calculating the cube histogram seems to leak memory. 

To reproduce:

- Open appimage. `carta_backend` starts with roughly 6 MB of memory utilised
- Load `supermosaic.10.fits`. `carta_backend` memory usage increases to around 66 MB
- Switch to cube histogram. During and after the calculation, memory increases to 125 MB
- Load the same file again. Memory increases to 185 MB
- Switch to cube histogram again. Memory increases to 245 MB
- Repeat. Each iteration adds up to 100 MB of memory usage, sometimes it doesn't. 

After a large number of repetitions, I managed to get memory usage up to 2 GB.

**Comment by pford** [comment]
After the changes in pull request #44, on macOSX Activity Monitor the backend memory usage for supermosaic cube histogram remained at 71.4 MB while loading, then returned to 42.1 MB when done.
