### ISSUE TITLE
[file info] error handle of broken image header

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#47]
Fatal Error [(NOT SET)]: Bad number of dimensions for ~/CARTA/Images/set_QA/broken_header.miriad in XYOPEN

Assertion failed: (err == 0), function uv_loop_delete, file src/uv-common.c, line 691.
Abort trap: 6

**Comment by pford** [comment]
There was no way to catch the casacore::MIRIADImage exception, had to directly call functions in casacore casa_mirlib library.  Fix is included in pull request #44 for release 1.0.
