### ISSUE TITLE
[file browser] beam information in file info 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#5]
beam information is missing in file information of file browser. Please also support the cases where per-plane-beam table exist (CASAMBM = True). We could report median value if there is no significant performance degradation.  

test image: under default path, "SDC335.579-0.292.spw0.line.image"

**Comment by duidae** [comment]
fixed in https://github.com/CARTAvis/nrao-carta-backend/pull/15, add restoring beam in file info
