### ISSUE TITLE
[imageViewer] black image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/nrao-carta-backend#7]
test image: set_OMC/orionkl_240894_line.pbcor.image

this image can be opened. xyz profilers seem to work fine, but the image is black.
![screen shot 2018-11-30 at 12 29 36 pm](https://user-images.githubusercontent.com/20819712/49268692-e2fade00-f49b-11e8-93e8-e9b52c188a5f.png)

**Comment by pford** [comment]
Backend now ignores nan and inf values for histogram.
